### ISSUE TITLE
Cancel Build (on menu bar) button does not get enabled while building

### ISSUE THREAD

**Issue by jluisestrada** [luminous-software/time-savers#5]
### Installed product versions
- Visual Studio: 2017 Ultimate
- This extension: [example 1.1.21]
- Resharper Ultimate 2017.1.1

### Description
While compiling, the Cancel Build button on the menu bar never gets enabled, so it is impossible the cancel the build

**Comment by yannduran** [comment]
Thanks for reporting this. As far as I can recall the 'Cancel Build' button has worked for me for quite a long time. I remember that I had to fiddle around to get the statuses updating properly, but that was quite some time ago.

Try updating to the latest version: v2.2.0.1 (I just checked and I can cancel a build with it). Visual Studio does sometimes seem to lag a little, and I've done the best I can to get it to refresh the button statuses as quickly as possible.

Hopefully the latest version will work for you, but please let me know if it doesn't.

**Comment by jluisestrada** [comment]
That's the version Im using :( 

Update:

And then, it suddenly started to work! 

I'll keep you posted if I note a pattern

**Comment by yannduran** [comment]
OK, thanks for the update.

Can we close this issue? You can always re-open it again later if you find a pattern
