### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by lennartb-** [luminous-software/time-savers#6]
The preview has been out for some time. If you need a hand I could try to find some free time to bump the version to support VS 2019.

**Comment by yannduran** [comment]
Hey, thanks for the offer of help! That's very kind of you!

Making a VS 2019 version available isn't that hard at all (just two changes in the vsix manifest). I've just had a couple of functions not working how they used to in VS 2017, and I didn't want to release a broken version.

I'm hoping to have a look this weekend. If I'm stuck after the weekend, I'll reach out to you. Thanks again!

**Comment by spottedmahn** [comment]
>a couple of functions not working how they used to in VS 2017

Which ones?  Maybe the community can help out?

**Comment by yannduran** [comment]
Thanks for the suggestion! I got it all worked out and v2.4 has been released for VS 2019.

I thought I had let @lennartb- know about the release, but it looks like I didn't. I'll close this issue now that VS 2019 support has been completed.

Thanks again to both of you!
