### ISSUE TITLE
License Link is Broken

### ISSUE THREAD

**Issue by spottedmahn** [luminous-software/time-savers#8]
### Installed product versions
N/A

### Description
The license link leads to a 404.

![image](https://user-images.githubusercontent.com/14079228/55402334-3734ce00-5521-11e9-94ff-5ff777c0e9d1.png)

https://marketplace.visualstudio.com/items?itemName=YannDuran.VisualStudioTimeSavers

I was unable to find the correct URL otherwise I would have submitted a PR 😊

**Comment by yannduran** [comment]
Thanks for that!

**Comment by yannduran** [comment]
I've removed the license link - thanks again!
