### ISSUE TITLE
Add a button to open the current Visual Studio instance's folder

### ISSUE THREAD

**Issue by yannduran** [luminous-software/time-savers#9]
From: https://github.com/madskristensen/ExtensibilityEssentials/issues/2

---

@yannduran thanks for the ping.

Installed, I can see this being useful! 😄

It would be nice if it showed the current instance's folder somewhere. This is something I seem to need quite regularly. E.g. open the folder like this:
C:\Users<user>\AppData\Local\Microsoft\VisualStudio\16.0_aabc1737\

Or simply output it on the Path Variables dump for copy/pasting?

---

Thanks @jcansdale! (I'd write Jamie, but I'm not sure if you'd be notified if I didn't add the @ handle)

I like your idea a lot, but it actually sounds like more of a perfect fit for Time Savers, rather than Extensibility Logs, because it's not really log-related (maybe I just named ET badly - I actually would have preferred Extensibility Essentials, but Mads had already used it lol).

Btw, you can add feature ideas, feedback etc on Extensibility Logs' GitHub repo. I opened a new issue for you for your suggestion.

Do you use Time Savers at all?

I'm happy to include your feature idea in ET if that's what extensibility developers would find handy though, for sure! I know I'll use it. And it means that I can get rid of the desktop shortcut that I currently use, lol.

What do you think @madskristensen> Extensibility Logs or Time Savers for Jamie

**Comment by madskristensen** [comment]
Tough one. I guess it makes sense for both, but given the extensibility need for access to that folder is probably higher than for other use cases, Extensibility Logs might be the more natural place for it

**Comment by yannduran** [comment]
OK, that's good enough for me! :-) _Extensibility Logs_ it is. Do you think may I should rename the extension to something like _Extensibility Tools_? No wait, you've already used that name too. Something else?

**Comment by yannduran** [comment]
This has been released in v1.3
